name: Build

on:
  push:
    branches:
      - main
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      # Setup Maven cache
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Build & Test
        run: mvn -B package

      - name: Publish to Sonatype
        run: |
          cat $GITHUB_WORKSPACE/settings.xml
          echo $GPG_SIGNING_KEY | base64 -d > signing.gpg
          gpg --batch --import signing.gpg
          mvn -B -DskipTests -s $GITHUB_WORKSPACE/settings.xml -P ossrh deploy
          rm -rf signing.gpg
          gpg --delete-keys
          gpg --delete-secret-keys
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}